#!/usr/bin/env bash
#=============================================================================
# Mango IoT Gateway Agent — Standalone Config Generator
#
# Generates /opt/gateway/config.yml without installing or running the agent.
# Use this to pre-configure before copying to the target device.
#
# Usage:
#   # Interactive
#   sudo bash configure.sh
#
#   # Automated
#   sudo bash configure.sh \
#     --server mqtt://your-server.com:1883 \
#     --mqtt-user iot \
#     --mqtt-pass MySecret123 \
#     --token prov-token-abc123 \
#     --device-id factory-gw-01 \
#     --name "Factory Gateway #1" \
#     --output ./config.yml
#
# Arguments:
#   --server URL      MQTT broker URL (required)
#   --mqtt-user USER  MQTT username
#   --mqtt-pass PASS  MQTT password
#   --token TOKEN     Provisioning token
#   --device-id ID    Unique device ID (default: auto from MAC)
#   --name NAME       Human-readable name
#   --output PATH     Output path (default: ./config.yml)
#   --help
#=============================================================================

set -u
set -o pipefail

# ============================================================================
# Defaults
# ============================================================================
OUTPUT="./config.yml"
SERVER=""
MQTT_USER=""
MQTT_PASS=""
TOKEN=""
DEVICE_ID=""
GW_NAME=""
TENANT_ID="default"

# ============================================================================
# Parse args
# ============================================================================
parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --server)     SERVER="$2"; shift 2 ;;
      --mqtt-user)  MQTT_USER="$2"; shift 2 ;;
      --mqtt-pass)  MQTT_PASS="$2"; shift 2 ;;
      --token)      TOKEN="$2"; shift 2 ;;
      --device-id)  DEVICE_ID="$2"; shift 2 ;;
      --name)       GW_NAME="$2"; shift 2 ;;
      --output)     OUTPUT="$2"; shift 2 ;;
      --help|-h)
        echo "Usage: bash configure.sh [options]"
        echo ""
        echo "Options:"
        echo "  --server URL      MQTT broker URL (e.g. mqtt://10.0.0.1:1883)"
        echo "  --mqtt-user USER  MQTT username"
        echo "  --mqtt-pass PASS  MQTT password"
        echo "  --token TOKEN     Provisioning token (from cloud UI)"
        echo "  --device-id ID    Unique device ID (auto from MAC if not set)"
        echo "  --name NAME       Human-readable name"
        echo "  --output PATH     Output path (default: ./config.yml)"
        echo "  --help            Show this help"
        echo ""
        echo "Example:"
        echo "  bash configure.sh --server mqtt://10.0.0.1:1883 --mqtt-user iot --mqtt-pass MyPass123"
        exit 0 ;;
      *) echo "Unknown: $1. See --help"; exit 1 ;;
    esac
  done
}

# ============================================================================
# Interactive prompts (if args not provided)
# ============================================================================
prompt_missing() {
  if [[ -z "${SERVER:-}" ]]; then
    echo ""
    echo "Enter MQTT broker URL from your cloud server:"
    read -r -p "  Server URL (mqtt://your-server.com:1883): " SERVER
    [[ -z "$SERVER" ]] && { echo "Server URL required"; exit 1; }
  fi

  if [[ -z "${DEVICE_ID:-}" ]]; then
    # Auto device ID from primary MAC if available
    local MAC=""
    if [[ -f /sys/class/net/eth0/address ]]; then
      MAC=$(cat /sys/class/net/eth0/address 2>/dev/null)
    elif [[ -f /sys/class/net/wlan0/address ]]; then
      MAC=$(cat /sys/class/net/wlan0/address 2>/dev/null)
    fi
    if [[ -n "$MAC" ]]; then
      DEVICE_ID="gw-$(echo "$MAC" | tr -d ':')"
      echo "  Device ID: $DEVICE_ID (auto from MAC)"
    else
      read -r -p "  Device ID (gw-xxxxxxxxxxxx): " DEVICE_ID
      DEVICE_ID="${DEVICE_ID:-gw-$(date +%s)}"
    fi
  fi

  [[ -z "${MQTT_USER:-}" ]] && read -r -p "  MQTT username (optional): " MQTT_USER
  [[ -z "${MQTT_PASS:-}" ]] && read -r -s -p "  MQTT password (optional): " MQTT_PASS && echo ""
  [[ -z "${TOKEN:-}" ]] && read -r -p "  Provisioning token (optional): " TOKEN
  [[ -z "${GW_NAME:-}" ]] && read -r -p "  Gateway name (optional): " GW_NAME
  GW_NAME="${GW_NAME:-Raspberry Pi Gateway}"
}

# ============================================================================
# Generate config
# ============================================================================
generate_config() {
  mkdir -p "$(dirname "$OUTPUT")"

  cat > "$OUTPUT" << YAML
# Mango IoT Gateway Agent Configuration
# Generated by configure.sh on $(date)

gateway:
  device_id: "${DEVICE_ID}"
  name: "${GW_NAME}"
  serial_number: ""
  tenant_id: "${TENANT_ID}"
  provision_token: "${TOKEN:-}"
  platform_url: ""

mqtt:
  broker_url: "${SERVER}"
  username: "${MQTT_USER:-}"
  password: "${MQTT_PASS:-}"
  client_id_prefix: "gw"
  ssl: false
  ca_cert: ""
  client_cert: ""
  client_key: ""
  qos: 1
  keep_alive: 60
  clean_session: true
  reconnect_delay: 5
  max_reconnect_delay: 60
  topics:
    telemetry: "gateway/{device_id}/telemetry"
    status: "gateway/{device_id}/status"
    log: "gateway/{device_id}/log"
    command: "gateway/{device_id}/command/set"
    response: "gateway/{device_id}/command/response"

modbus:
  enabled: false
  devices: []

gpio:
  enabled: false
  sensors: []

monitoring:
  interval: 30
  cpu: true
  memory: true
  disk: true
  temperature: true
  network: true
  disk_threshold_warn: 90
  memory_threshold_warn: 90
  cpu_threshold_warn: 90
  temp_threshold_warn: 80

logging:
  level: "info"
  file: "/var/log/gateway-agent.log"
  max_size: 10
  max_backups: 7
  remote: true

ota:
  enabled: true
  firmware_dir: "/opt/gateway/firmware"
  backup_dir: "/opt/gateway/backup"
  auto_rollback: true
  rollback_timeout: 30

watchdog:
  enabled: true
  interval: 60
  max_missed_pings: 3
  action: "restart"

commands:
  enabled: true
  allowed:
    - "reboot"
    - "restart_agent"
    - "run_shell"
    - "update_firmware"
    - "set_relay"
    - "read_register"
  shell:
    allowed_paths:
      - "/opt/gateway/scripts/"
      - "/usr/local/bin/"
    timeout: 30
YAML

  echo ""
  echo "Config generated: $OUTPUT"
  echo ""
  echo "To deploy:"
  echo "  1. Copy config.yml and gateway-agent binary to the target device"
  echo "  2. On the device, run setup.sh or manually place files"
  echo ""
  echo "  Example:"
  echo "    scp $OUTPUT gateway-agent pi@YOUR_PI:~/"
  echo "    ssh pi@YOUR_PI 'sudo mv config.yml /opt/gateway/ && sudo mv gateway-agent /usr/local/bin/'"
}

# ============================================================================
# Main
# ============================================================================
main() {
  parse_args "$@"
  prompt_missing
  generate_config
}

main "$@"
